// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHeV2faA9HZgoUFaUt7Ps7_rJzekk2ro',
    appId: '1:233617058564:web:d49899ccb474312c413e51',
    messagingSenderId: '233617058564',
    projectId: 'sp3a-f4e45',
    authDomain: 'sp3a-f4e45.firebaseapp.com',
    storageBucket: 'sp3a-f4e45.firebasestorage.app',
    measurementId: 'G-6QDS2H7SZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrneO6v_1Dh8fFxObizEhSTUMN-OKbDY',
    appId: '1:233617058564:android:9cee99bf96e5a361413e51',
    messagingSenderId: '233617058564',
    projectId: 'sp3a-f4e45',
    storageBucket: 'sp3a-f4e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rlz64T0olMPMRE8UH7DQMKBfYAfETyc',
    appId: '1:233617058564:ios:f3a44e4847bd2a38413e51',
    messagingSenderId: '233617058564',
    projectId: 'sp3a-f4e45',
    storageBucket: 'sp3a-f4e45.firebasestorage.app',
    iosBundleId: 'com.sp3a.sp3aProjek',
  );
}
